---
apiVersion: v1
kind: Namespace
metadata:
  name: busybox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata
  namespace: busybox
  labels:
    app: busybox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-nas-svm2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: quay.io/trident-mirror/kcduk/busybox:1.31.1
        imagePullPolicy: IfNotPresent
        command: ['sleep', '3600']        
        volumeMounts:
        - mountPath: /data
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mydata
