apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot
  namespace: busybox
  labels:
    app: busybox
spec:
  volumeSnapshotClassName: csi-snapclass
  source:
    persistentVolumeClaimName: mydata
